version: '3.8'

services:
  database:
    container_name: dest-database
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: symfony_docker
      MYSQL_USER: symfony
      MYSQL_PASSWORD: symfony
    ports:
      - '4306:3375'
    volumes:
      - ./mysql:/var/lib/mysql
    networks:
      - dest-network

  php:
    container_name: dest-php
    build:
      context: ./php
    ports:
      - '9075:9000'
    volumes:
      - ../app:/var/www/symfony_docker
    depends_on:
      - database
    networks:
      - dest-network

  nginx:
    container_name: dest-nginx
    image: nginx:stable-alpine
    ports:
      - '8075:80'
    volumes:
      - ../app:/var/www/symfony_docker
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - database
    networks:
      - dest-network

networks:
  dest-network:
    driver: bridge
